#if !canImport(ObjectiveC)
import XCTest

extension ASTDebugDescriptionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ASTDebugDescriptionTests = [
        ("testDebugDescription", testDebugDescription),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ASTDebugDescriptionTests.__allTests__ASTDebugDescriptionTests),
    ]
}
#endif
