#if !canImport(ObjectiveC)
import XCTest

extension ExecutorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExecutorTests = [
        ("testExecuteDeterministicProgramWithLoop", testExecuteDeterministicProgramWithLoop),
        ("testExecuteMultiStatementProgram", testExecuteMultiStatementProgram),
        ("testExecuteProbabilisticProgram", testExecuteProbabilisticProgram),
        ("testExecuteProbabilisticProgramWithIf", testExecuteProbabilisticProgramWithIf),
        ("testExecuteSingleStatementProgram", testExecuteSingleStatementProgram),
        ("testGenerateGeometricDistribution", testGenerateGeometricDistribution),
    ]
}

extension HistoryExecutorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HistoryExecutorTests = [
        ("testExecuteMultiStatementProgram", testExecuteMultiStatementProgram),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExecutorTests.__allTests__ExecutorTests),
        testCase(HistoryExecutorTests.__allTests__HistoryExecutorTests),
    ]
}
#endif
