#if !canImport(ObjectiveC)
import XCTest

extension DebuggerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DebuggerTests = [
        ("testExecuteProbabilisticProgramWithIf", testExecuteProbabilisticProgramWithIf),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DebuggerTests.__allTests__DebuggerTests),
    ]
}
#endif
