#if !canImport(ObjectiveC)
import XCTest

extension HistoryInferenceEngineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HistoryInferenceEngineTests = [
        ("testLoop", testLoop),
        ("testProbStatement", testProbStatement),
        ("testStepOverStraightLineProgram", testStepOverStraightLineProgram),
    ]
}

extension InferenceEngineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InferenceEngineTests = [
        ("testExecuteDeterministicProgramWithLoop", testExecuteDeterministicProgramWithLoop),
        ("testExecuteMultiStatementProgram", testExecuteMultiStatementProgram),
        ("testExecuteProbabilisticProgram", testExecuteProbabilisticProgram),
        ("testExecuteProbabilisticProgramWithIf", testExecuteProbabilisticProgramWithIf),
        ("testExecuteSingleStatementProgram", testExecuteSingleStatementProgram),
        ("testGenerateGeometricDistribution", testGenerateGeometricDistribution),
    ]
}

extension TermTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TermTests = [
        ("testAdditionListEntriesWithZeroTermsGetRemoved", testAdditionListEntriesWithZeroTermsGetRemoved),
        ("testAdditionListMergesConditions", testAdditionListMergesConditions),
        ("testAdditionListMergesConditionsInTwoSteps", testAdditionListMergesConditionsInTwoSteps),
        ("testAdditionOfVariableWithZero", testAdditionOfVariableWithZero),
        ("testMergeDuplicateEntriesWithDifferentFactors", testMergeDuplicateEntriesWithDifferentFactors),
        ("testRecursivelySimplifyAdditionList", testRecursivelySimplifyAdditionList),
        ("testSimplify", testSimplify),
        ("testZeroDividedByZeroIsZero", testZeroDividedByZeroIsZero),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HistoryInferenceEngineTests.__allTests__HistoryInferenceEngineTests),
        testCase(InferenceEngineTests.__allTests__InferenceEngineTests),
        testCase(TermTests.__allTests__TermTests),
    ]
}
#endif
